### PR TITLE
Feat/third party

### PR DESCRIPTION
**Pull request by Roms1383**
Example on how to leverage third-party native plugin with Codeware.

### CODE REVIEW

**Comment by Roms1383** [comment]
If you want I can add comments to help people fully understand how to come up with their own bindings, I think it would be a nice to have addition @jac3km4.

**Comment by jac3km4** [comment]
@Roms1383 I think the examples should be broken down into individual one or two function mods, the current examples aren't great because it's one massive file with functions that don't do anything interesting, I'd remove the current example and replace it with stuff like
- example that opens a popup or some other interaction
- example that adds an item to the inventory
- etc

**Comment by Roms1383** [comment]
I agree but the point of this example is to show that we're already able to vamp from other native libs while waiting for them to be natively implemented directly in `red4ext-rs`. Maybe I break it down into a separate example called e.g. `third-party`? And we can still add more examples in the future like the ones you rightfully stated, what do you think @jac3km4?

**Comment by Roms1383** [comment]
Maybe an example with Codeware providing some kind of event subscriber / dispatcher would be interesting ?
Or any of the other features that Codeware provides if you have a better use case in mind @jac3km4.

**Comment by jac3km4** [comment]
@Roms1383 should I close this PR, it' out of date

**Pull request closed without merging**
